# ====================== GENERAL ======================
[shell]

program = "/bin/zsh"
args = ["-l", "-c", "zellij attach || zellij"]

# ====================== ENV ======================
[env]

TERM = "xterm-256color"

# ====================== WINDOW ======================
[window]

# Opacity
opacity = 0.9  # Default: 1.0

decorations = "None"  # Default: "Full"

startup_mode = "Maximized"  # Default: "Windowed"

# ====================== COLOR ======================
# NOTE: The following color settings comes from "ayu_dark" schema
# ref. https://github.com/alacritty/alacritty-theme

# Default colors
[colors.primary]
background = '#0A0E14'
# foreground = '#B3B1AD'
foreground = '#EEEEEE'

# Normal colors
[colors.normal]
black   = '#01060E'
red     = '#EA6C73'
green   = '#91B362'
yellow  = '#F9AF4F'
blue    = '#53BDFA'
magenta = '#FAE994'
cyan    = '#90E1C6'
white   = '#C7C7C7'

# Bright colors
[colors.bright]
black   = '#686868'
red     = '#F07178'
green   = '#C2D94C'
yellow  = '#FFB454'
blue    = '#59C2FF'
magenta = '#FFEE99'
cyan    = '#95E6CB'
white   = '#FFFFFF'

# ====================== FONT ======================
[font]

# Normal font style
normal = { family = "Menlo", style = "Regular" }  # Default for Linux/BSD: "monospace", Regular

# Font size in points
# size = 10 # Default: 11.25
# size = 12 # Default: 11.25
size = 14.5  # Default: 11.25

offset.x = 0  # For letter spacing. Default: 0
offset.y = 1  # For line spacing. default: 0

# ====================== CURSOR ======================
[cursor]

# Cursor style
style = { shape = "Block", blinking = "On" }  # Default: shape = "Block", blinking = "Off"

# ====================== MOUSE ======================
[mouse]

# When true, the cursor is temporarily hidden when typing
hide_when_typing = true  # Default: false

# ====================== KEYBOARD ======================
[keyboard]

bindings = [
    # { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
    # { key = "L", mods = "Control|Shift", chars = "l" },
    { key = "Space", mods = "Command", action = "Quit" },
]
